dependencies:
  - name: helm-toolkit-contrail
    repository: '@local'
    version: 0.1.0
  - name: contrail-thirdparty
    repository: '@local'
    version: 0.1.0
  - name: contrail-controller
    repository: '@local'
    version: 0.1.0
  - name: contrail-analytics
    repository: '@local'
    version: 0.1.0
  - name: contrail-vrouter
    repository: '@local'
    version: 0.1.0
